# Generated by Django 3.2.5 on 2022-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=500, unique=True)),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(choices=[('EN STOCK', 'En stock'), ('SIN STOCK', 'Sin stock')], max_length=15)),
                ('Imagenes', models.ImageField(upload_to='product-images')),
            ],
        ),
    ]
