# Generated by Django 3.2.5 on 2022-10-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
