# Generated by Django 3.2.5 on 2022-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Estado',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Off stock', 'Off stock')], max_length=15),
        ),
    ]
