# Generated by Django 3.2.5 on 2022-10-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product-images')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Imagenes',
            new_name='primaryImage',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Estado',
            new_name='state',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.images'),
        ),
    ]
