# Generated by Django 3.2.5 on 2022-10-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221027_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(null=True, upload_to='product-images'),
        ),
    ]
