# Generated by Django 3.2.5 on 2022-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221028_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Actualizar', max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Off stock', 'Off stock')], max_length=10),
        ),
    ]
